# Fish frozen theme (generated by fish_config web tool)
# Location: ~/.config/fish/conf.d/fish_frozen_theme.fish

set --global fish_color_autosuggestion 747369
set --global fish_color_cancel --reverse
set --global fish_color_command 99cc99
set --global fish_color_comment ffcc66
set --global fish_color_cwd green
set --global fish_color_cwd_root red
set --global fish_color_end cc99cc
set --global fish_color_error f2777a
set --global fish_color_escape 66cccc
set --global fish_color_history_current --bold
set --global fish_color_host --reset
set --global fish_color_host_remote yellow
set --global fish_color_normal --reset
set --global fish_color_operator 6699cc
set --global fish_color_param d3d0c8
set --global fish_color_quote ffcc66
set --global fish_color_redirection d3d0c8
set --global fish_color_search_match white --bold --background=brblack
set --global fish_color_selection white --bold --background=brblack
set --global fish_color_status red
set --global fish_color_user brgreen
set --global fish_color_valid_path --underline=single
set --global fish_pager_color_completion --reset
set --global fish_pager_color_description B3A06D
set --global fish_pager_color_prefix --bold --underline=single
set --global fish_pager_color_progress brwhite --bold --background=cyan
set --global fish_pager_color_selected_background --background=brblack
set --global fish_pager_color_selected_completion
set --global fish_pager_color_selected_description
set --global fish_pager_color_selected_prefix
